name: ServiceA build
on:
  pull_request:
    paths-ignore:
      - 'ServiceA/**'
      - 'ServiceB/**'
      - 'ServiceC/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
